 ---
functional:
  - Сайт должен быть адаптирован под мобильные устройства
  - У пользователя должна быть возможность создавать игру
  - У пользователя должна быть возможность выбирать язык программирования во время игры
  - У пользователя должна быть возможность писать в чат во время игры
  - При смене уровня сложности должен менятся список заданий
  - На сайте должна быть возможность просмотра таблицы лидеров
  - У пользователя должна быть возможность просмотра истории завершенных игр
  - У пользователя должна быть возможность предложить игру другому пользователю находящемуся в комнате ожидания (lobby)
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Должна быть возможность отфильтровать игры с ботами и игры против пользователей в списке лидеров
  - Для того чтоб учавствовать в играх нужно быть зарегестрированным на https://codebattle.hexlet.io/
  - Человек которому вы скидываете ссылку на игру должен быть зарегестрирован на https://codebattle.hexlet.io/
